server:
  port: 9002
spring:
  application:
    name: license-plate-service

eureka:
  client:
    service-url:
      defaultZone: http://xhwl:xhwl2020@localhost:10000/eureka
    registry-fetch-interval-seconds: 5 #修改拉取周期5s
  instance:
    prefer-ip-address: true
    ip-address: 127.0.0.1
    lease-renewal-interval-in-seconds: 5 #修改心跳为5s
    lease-expiration-duration-in-seconds: 15 #修改过期时间

logging:
  level:
    com.xhwl.licensePlate: debug
huaweiCloud:
  userName:  #华为云账户
  passWord:  #华为云密码
  domainName:  #华为云IAM（个人用户基就是华为云账户）
