server:
  port: 9005
spring:
  application:
    name: uploadAndDownload-service
eureka:
  client:
    service-url:
      defaultZone: http://xhwl:xhwl2020@localhost:10000/eureka
    registry-fetch-interval-seconds: 5 #修改拉取周期5s
  instance:
    prefer-ip-address: true
    ip-address: 127.0.0.1
    lease-renewal-interval-in-seconds: 5 #修改心跳为5s
    lease-expiration-duration-in-seconds: 15 #修改过期时间
logging:
  level:
    com.xhwl: debug
huawei:
  tokenUrl: https://studio.e.huawei.com/baas/auth/v1.0/oauth2/token?grant_type=client_credentials&client_id=b912c749275d43ecb57ee68ce99a9d65&client_secret=dbe9db27898ae54ced833e11273e2f5ecba5808149f3dc78
  excelUrl: https://studio.e.huawei.com/service/xhiot__FSoil/1.0.0/excelUploadData
