server:
  port: 9000
spring:
  application:
    name: gateway-service
  redis:
    host: 127.0.0.1
eureka:
  client:
    service-url:
      defaultZone: http://xhwl:xhwl2020@localhost:10000/eureka
    registry-fetch-interval-seconds: 5 #修改拉取周期5s
  instance:
    prefer-ip-address: true
    ip-address: 127.0.0.1
    lease-renewal-interval-in-seconds: 5 #修改心跳为5s
    lease-expiration-duration-in-seconds: 15 #修改过期时间


zuul:
  host:
    connect-timeout-millis: 15000 #HTTP连接超时要比Hystrix的大
    socket-timeout-millis: 6000   #socket超时
  prefix: /api # 添加路由前缀
  routes:
    license-plate-service: /license_plate/**
    user-service: /user/**
    auth-service: /oauth/**
  sensitive-headers:
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 6000 # 熔断超时时长：6000ms


ribbon:
  ConnectTimeout: 10000 # ribbon链接超时时长
  ReadTimeout: 20000 # ribbon读取超时时长
  MaxAutoRetries: 0  # 当前服务重试次数
  MaxAutoRetriesNextServer: 1 # 切换服务重试次数
  OkToRetryOnAllOperations: false # 是否对所有的请求方式都重试，只对get请求重试
xh:
  cors:
    allowedOrigins:
      - http://locahost
      - http://127.0.0.1
    allowCredentials: true
    allowedHeaders:
      - "*"
    allowedMethods:
      - GET
      - POST
      - DELETE
      - PUT
      - OPTIONS
      - HEAD
    maxAge: 3600
    filterPath: "/**"
  filter:
    allowPaths:
      - /api/oauth/oauth/login
      - /api/oauth/oauth/logout
      - /api/user/xhwl/register
      - /api/user/xhwl/send/email
  cookieDomain: localhost
